# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'HearHereApp' do
source 'https://github.com/CocoaPods/Specs.git'
pod 'Alamofire', '~> 1.1'

pod 'OCMapper'
end

target 'HearHereAppTests' do

end

