# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'

target 'HearHereApp' do
  pod 'Alamofire', '~> 1.2'
  pod 'OCMapper'
  pod 'HanekeSwift'
end

target 'HearHereAppTests' do

end

